#!/usr/bin/env bash
set -e

DEST=$1
BINARY_NAME="netrack"

# Build binary with embedded version string
GOFLAGS="-X main.version ${VERSION}-${REVISION}"
GOTAGS=

# Build executable
go build -o "${DEST}/${BINARY_NAME}" -tags="${GOTAGS}" -ldflags="${GOFLAGS}"

echo "=== INFO: Created binary at ${DEST}/${BINARY_NAME}"
