#!/bin/bash
set -e

# go test command options
GOFLAGS="-v"

# List of packages to ignore
IGNORE=.git

# Make race check available only for 64-bit platforms
if [ -n "$(uname -i | grep -E "(amd64|x86_64)")" ]; then
    GOTAGS="${GOTAGS} -race"
fi

# Go throught project hierarchy and run tests where they are found.
for package in $(find -name "${IGNORE}" -prune -o -type d); do
    TESTS=$(ls -l ${package}/*_test.go 2>/dev/null | xargs)

    if [ -z "${TESTS}" ]; then
        echo "=== WARN: Skipping ${package}"
        continue
    fi

    echo "=== INFO: Testing package ${package}"
    go test ${GOFLAGS} -tags="test" "${package}"
done
