# Netrack configuration file
#
instance_id = "2ba5e6cc-c5bb-11e4-a23c-001fd08d7e6c"
#
# Server bind address
host = "tcp://0.0.0.0:6633"

# Netrack database configuration
[database.development]
user = "netrack-user"
password = "netrack"
dbname = "netrack-test"
sslmode = "disable"

[database.production]
# user = "netrack-user"
# password = "netrack"
# dbname = "netrack-dev"
# sslmode = "disable"

[database.test]
user = "netrack-user"
password = "netrack"
dbname = "netrack-test"
sslmode = "disable"
